# Generated by Django 6.0.8 on 2026-08-04 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('GNews_title', models.CharField(max_length=500)),
                ('Diffbot_title', models.CharField(blank=True, max_length=500)),
                ('siteName', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=1000)),
                ('validado', models.CharField(choices=[('VALIDO', 'VALIDO'), ('NO RELEVANTE', 'NO RELEVANTE'), ('SIN REVISAR', 'SIN REVISAR')], default='SIN REVISAR', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='main.article')),
            ],
        ),
    ]
